### ISSUE TITLE
ViewImageInfo doesn't work properly with another extension lately

### ISSUE THREAD

**Issue by rado84-github** [jscher2000/View-Image-Info-Reborn-for-Firefox#4]
Other than Vii, I'm also using an extension named "Search image on TinEye" and it works like Vii with right click on the image. Until recently I was able to use Vii to open an image (especially on Instagram and other JS websites) in a new window and then right click it to launch a search for the same image on TinEye (for better quality and larger sizes). At first I thought that the TinEye's extension was not working but I tested it in several different situations and it works. After a lot of testing, it seems that whatever image is open through Vii, the TinEye's extension no longer recognizes it as an image.

If you could do something about that issue, it would be great.

**Comment by jscher2000** [comment]
> After a lot of testing, it seems that whatever image is open through Vii, the TinEye's extension no longer recognizes it as an image.

Firefox restricts extensions from running in one another's pages. I don't think I'm going to be able to work around that (or at least my initial searches have not uncovered any workaround).

That said, it looks like the way the TinEye extension works is to send the full URL of the image to a public search page on the TinEye site. I think I could add a button for that if it wouldn't violate any policy of the site.

Otherwise, you still should be able to run the search from the original image.

**Comment by rado84-github** [comment]
> 

The problem is that Instagram uses some kind of a JS that prevents the browser to recognize the image as such. If you right click any image on instagram, it displays options such as "save as..." (saves it as html), "save to pocket", "save page as...". If the browser were recognizing it as an image, it would display options like "image properties", "save image as..." and so on. For this reason I can't run the search from the original image on instagram and I have to use your extension to get to the actual image.

I doubt that you would violate any policy of TinEye by addin a button for that, since it will resemble the way their extension works.

**Comment by jscher2000** [comment]
I added a button for TinEye reverse image search in the popup (between Save and Print). Let me know how it works for you.

**Comment by rado84-github** [comment]
Works perfectly! Thanks! :D
